In [ ]:
Que.1.Is there any difference in the data type of variables list_& array_list?If there is then write
      a code to print the data types of both the variables.

In [1]:
import numpy as np

variable_list=['1','2','3','4','5']
array_list=np.array(object=list)

print("Data type of variable_list:",type(variable_list))
print("Data type of array_list:",type(array_list))


Data type of variable_list: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [ ]:
Que.2.Write a code to print the data tyape of each & every element of both the variables_list &
      array_list.

In [4]:
import numpy as np

variable_list=['1','2','3','4','5']
array_list=np.array([1,2,3,4,5])

print("Data types of element in variable_list:")
for element in variable_list:
    print(f"Element:{element},Data type:{type(element)}")
    
print("\nData types of element in array_list:")
for element in array_list:
    print(f"Element:{element},Data type:{type(element)}")
    

Data types of element in variable_list:
Element:1,Data type:<class 'str'>
Element:2,Data type:<class 'str'>
Element:3,Data type:<class 'str'>
Element:4,Data type:<class 'str'>
Element:5,Data type:<class 'str'>

Data types of element in array_list:
Element:1,Data type:<class 'numpy.int64'>
Element:2,Data type:<class 'numpy.int64'>
Element:3,Data type:<class 'numpy.int64'>
Element:4,Data type:<class 'numpy.int64'>
Element:5,Data type:<class 'numpy.int64'>


In [ ]:
Que.3.Write a code to find the following characteristics of variable,num_array:1.shape.2.size.

In [5]:
import numpy as np

variable_list=[1,2,3,'a','b',4.5]
array_list=np.array([1,2,3,4,5])

print("Shape & size characteristics of variable_list:")
print(f"Lenght:{len(variable_list)}")
print(f"Type:{type(variable_list)}")

print("\nShape & size characteristics of array_list:")
print(f"Shape:{array_list.shape}")
print(f"Size:{array_list.size}")
print(f"Number of dimensions:{array_list.ndim}")
print(f"Type:{type(array_list)}")

Shape & size characteristics of variable_list:
Lenght:6
Type:<class 'list'>

Shape & size characteristics of array_list:
Shape:(5,)
Size:5
Number of dimensions:1
Type:<class 'numpy.ndarray'>


In [ ]:
Que.4.write a code to create numpy array of 3*3 matrix containing zeros only,using a numpy array
      creation function.

In [6]:
import numpy as np

array_zeros=np.zeros((3,3))
print(array_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
Que.5.Create an identity matrix of shape(5,5)using numpy function. 

In [ ]:
import numpy as np

identity_matr